/*
 * This source file was generated by the Gradle 'init' task
 */
package org.url;

public class UrlLibrary {
    public boolean someLibraryMethod() {
        return true;
    }
    public String libraryGreeting() {
        return "Hello library working fine !!!";
    }

}
