package org.app;/*
 * This source file was generated by the Gradle 'init' task
 */

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.utils.CustomGenerator;

@SpringBootApplication
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        CustomGenerator customGenerator = new CustomGenerator();

        for (int i = 1; i <= 26 * 26; i ++) {
            System.out.println(customGenerator.generateId(i));
        }
    }
}
