/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.url.UrlLibrary;

public class App {
    public static void main(String[] args) {
        UrlLibrary library = new UrlLibrary();
        System.out.println(library.libraryGreeting());
    }
}
