/*
 * This source file was generated by the Gradle 'init' task
 */
package org.tokens;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import static org.junit.jupiter.api.Assertions.*;

class CustomComponentsTest {
    private final CustomGenerator customGenerator = new CustomGenerator();

    @Test
    void testCustomGenerateIdOrder1() {
        int asciiOfA = 'a';

        assertEquals("b", customGenerator.generateId(1));

        for (int i = 0; i <= 25; i++) {
            char c = (char) (asciiOfA + i);
            String id = customGenerator.generateId(i);
            assertEquals(Character.toString(c), id, "the id generation does not work for one number from 0 to 25");
        }

    }

    @Test
    void testCustomGenerateIdOrder2() {
        int asciiOfA = 'a';

        int i1 = 10;
        int i2 = 4;

        for (int j = 1; j < 26; j++) {
            int order = 26 * j + i1;
            String id = customGenerator.generateId(order);
            char c1 = (char) (asciiOfA + j);

            char c2 = (char) (asciiOfA + i1);
            assertEquals(c1 + Character.toString(c2), id);

            order = 26 * j + i2;
            id = customGenerator.generateId(order);
            char c3 = (char) (asciiOfA + i2);
            assertEquals(c1 + Character.toString(c3), id);
        }
    }

    @Test
    // TODO: make the verify_power_26 private and access it through reflection in the tests...
    void testCustomerGeneratorPowers26() throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
        for (int i = 1; i <= 6; i++) {
            long power26 = (long) Math.pow(26, i);

            Method m = customGenerator.getClass().getDeclaredMethod("verify_power_26", long.class);
            m.setAccessible(true);
            assertEquals(i , (int) m.invoke(customGenerator, power26));

            String id = customGenerator.generateId(power26);
            String realId = "b" + "a".repeat(i);
            assertEquals(realId, id, "it does not work with powers of 26...");
        }
    }

    @Test
    // the test takes some time to run: however the current implementation passes
    void testIdNumberConversion() {
        for (long i = 0; i <= (long) Math.pow(26,3); i++) {
            String id = customGenerator.generateId(i);
            long numberId = customGenerator.orderFromId(id);
            assertEquals(i, numberId);
        }
    }

}
