/*
 * This source file was generated by the Gradle 'init' task
 */
package app;

import org.utils.CustomGenerator;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        CustomGenerator customGenerator = new CustomGenerator();
        System.out.println(customGenerator.generateId(26));
    }
}
