/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.url.UrlValidator;

import static org.junit.jupiter.api.Assertions.*;

class UrlLibraryTests {

    private final UrlValidator urlValidator = new UrlValidator();

    @Test
    void testValidUrls() {
        // valid urls
        String s1 = "https://youtube.com";
        String s2 = "https://github.com/ayhem18/Towards_Data_Science/blob/main/Programming_Tools/Databases/Practice/sqlpad";

        assertDoesNotThrow(() -> urlValidator.validateUrl(s1));
        assertDoesNotThrow(() -> urlValidator.validateUrl(s2));

    }

    @Test void testInvalidUrls() {

        // invalid urls
        String s3 = "https://github.com/ayhem 18";
		String s4 = "https://github.c/ayhem18";

        assertThrows(UrlValidator.InvalidUrlException.class, () -> urlValidator.validateUrl(s3));
        assertThrows(UrlValidator.InvalidUrlException.class, () -> urlValidator.validateUrl(s4));

    }
}
