/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    private final UrlValidator urlValidator = new UrlValidator();

    @Test
    void testValidUrls() {
        String s1 = "https://youtube.com";
        String s2 = "https://github.com/ayhem18/Towards_Data_Science/blob/main/Programming_Tools/Databases/Practice/sqlpad";

        assertDoesNotThrow(() -> this.urlValidator.validateUrl(s1));
        assertDoesNotThrow(() -> this.urlValidator.validateUrl(s2));
    }

    @Test void testUnvalidUrls() {
        String s1 = "https://github.com/ayhem 18";
        String s2 = "https://github.co/ayhem18";


        assertThrows(UrlValidator.InvalidUrlException.class,() -> this.urlValidator.validateUrl(s1));
        assertThrows(UrlValidator.InvalidUrlException.class,() -> this.urlValidator.validateUrl(s2));
    }
}
